version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install packages
          command: npm install
      - run:
          name: run tests
          command: npx jest
workflows:
  workflow:
    jobs:
      - build_and_test
