version: 2.1
jobs:
  build_and_test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
         keys:
           - v1-{{ checksum "package-lock.json" }}
      - run:
          name: install packages
          command: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths: .
      - run:
          name: run tests
          command: npx jest
      
workflows:
  workflow:
    jobs:
      - build_and_test
